#!/usr/bin/env bash
#MISE alias="rn"
#MISE depends=["build"]

cp Sources/CRaylib/libEGL.dylib "$build_dir/debug/" 2>/dev/null || true
cp Sources/CRaylib/libGLESv2.dylib "$build_dir/debug/" 2>/dev/null || true
"$build_dir/debug/$binary_name"
